/* Generated By:JavaCC: Do not edit this line. Example2TreeConstants.java Version 7.0.12 */
public interface Example2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=9835c7d444d66e080d1a14086d500493 (do not edit this line) */
