/* Generated By:JavaCC: Do not edit this line. Example1TreeConstants.java Version 7.0.12 */
public interface Example1TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTADDITIVEEXPRESSION = 2;
  public int JJTMULTIPLICATIVEEXPRESSION = 3;
  public int JJTUNARYEXPRESSION = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=b00f648bb407a8efe1fdb21431ec639c (do not edit this line) */
