/* Generated By:JavaCC: Do not edit this line. Example3TreeConstants.java Version 7.0.12 */
public interface Example3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=2548fee8d747c20b6439b555d1f07a7a (do not edit this line) */
