/* Generated By:JavaCC: Do not edit this line. Example4TreeConstants.java Version 7.0.12 */
public interface Example4TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYOTHERID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyOtherID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=c47969501e919422b36e560617ede24b (do not edit this line) */
