/* Generated By:JavaCC: Do not edit this line. Example4Visitor.java Version 7.0.12 */
public interface Example4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=c0d79459da463a34e5a1bde675c63a01 (do not edit this line) */
