/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package piat.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FECHA = 5;
  /** RegularExpression Id. */
  int HORA = 6;
  /** RegularExpression Id. */
  int TIPO_SERVIDOR = 7;
  /** RegularExpression Id. */
  int NUMERO_SERVIDOR = 8;
  /** RegularExpression Id. */
  int MENSAJE = 9;
  /** RegularExpression Id. */
  int MSG_IN = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<FECHA>",
    "<HORA>",
    "<TIPO_SERVIDOR>",
    "<NUMERO_SERVIDOR>",
    "<MENSAJE>",
    "<MSG_IN>",
  };

}
