/* Generated By:JavaCC: Do not edit this line. GramaticaTreeConstants.java Version 7.0.12 */
package Analizador;

public interface GramaticaTreeConstants
{
  public int JJTJSON = 0;
  public int JJTOBJECT = 1;
  public int JJTARRAY = 2;
  public int JJTPAIR = 3;
  public int JJTVALUE = 4;


  public String[] jjtNodeName = {
    "json",
    "object",
    "array",
    "pair",
    "value",
  };
}
/* JavaCC - OriginalChecksum=45b0df3b2d4784b051db10fd19f2d1b0 (do not edit this line) */
