/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GRAPHS = 7;
  /** RegularExpression Id. */
  int CONCEPT_ID = 8;
  /** RegularExpression Id. */
  int TITLE = 9;
  /** RegularExpression Id. */
  int LINK = 10;
  /** RegularExpression Id. */
  int EVENT_LOCATION = 11;
  /** RegularExpression Id. */
  int AREA = 12;
  /** RegularExpression Id. */
  int LATITUDE = 13;
  /** RegularExpression Id. */
  int LONGITUDE = 14;
  /** RegularExpression Id. */
  int ACCESIBILITY = 15;
  /** RegularExpression Id. */
  int ORGANIZATION_NAME = 16;
  /** RegularExpression Id. */
  int DESCRIPTION = 17;
  /** RegularExpression Id. */
  int ID_RESOURCE = 18;
  /** RegularExpression Id. */
  int ARRAY_START = 19;
  /** RegularExpression Id. */
  int ARRAY_END = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int INTEGER = 22;
  /** RegularExpression Id. */
  int DOUBLE = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int NULL = 26;
  /** RegularExpression Id. */
  int ID_AREA = 27;

  /** Lexical state. */
  int ARRAYGRAPH = 0;
  /** Lexical state. */
  int DETECT = 1;
  /** Lexical state. */
  int INRESOURCE = 2;
  /** Lexical state. */
  int DEFAULT = 3;
  /** Lexical state. */
  int GRAPH = 4;
  /** Lexical state. */
  int INAREA = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\":\"",
    "\"\\\"@graph\\\"\"",
    "\"\\\"@type\\\"\"",
    "\"\\\"title\\\"\"",
    "\"\\\"relation\\\"\"",
    "\"\\\"street-address\\\"\"",
    "\"\\\"area\\\"\"",
    "\"\\\"latitude\\\"\"",
    "\"\\\"longitude\\\"\"",
    "\"\\\"accesibility\\\"\"",
    "\"\\\"organization-name\\\"\"",
    "\"\\\"services\\\"\"",
    "\"\\\"@id\\\"\"",
    "\"[\"",
    "\"]\"",
    "<STRING>",
    "<INTEGER>",
    "<DOUBLE>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"\\\"@id\\\"\"",
    "<token of kind 28>",
  };

}
