/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GRAPHS = 14;
  /** RegularExpression Id. */
  int CONCEPT_ID = 15;
  /** RegularExpression Id. */
  int TITLE = 16;
  /** RegularExpression Id. */
  int LINK = 17;
  /** RegularExpression Id. */
  int EVENT_LOCATION = 18;
  /** RegularExpression Id. */
  int AREA = 19;
  /** RegularExpression Id. */
  int LATITUDE = 20;
  /** RegularExpression Id. */
  int LONGITUDE = 21;
  /** RegularExpression Id. */
  int ACCESIBILITY = 22;
  /** RegularExpression Id. */
  int ORGANIZATION_NAME = 23;
  /** RegularExpression Id. */
  int DESCRIPTION = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int ORGANIZATION_STRING = 26;
  /** RegularExpression Id. */
  int ID_RESOURCE = 27;
  /** RegularExpression Id. */
  int ARRAY_START = 28;
  /** RegularExpression Id. */
  int ARRAY_END = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int INTEGER = 31;
  /** RegularExpression Id. */
  int DOUBLE = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int NULL = 35;
  /** RegularExpression Id. */
  int ID_AREA = 36;

  /** Lexical state. */
  int ARRAYGRAPH = 0;
  /** Lexical state. */
  int DETECT = 1;
  /** Lexical state. */
  int INRESOURCE = 2;
  /** Lexical state. */
  int ENDOFRESOURCE = 3;
  /** Lexical state. */
  int DEFAULT = 4;
  /** Lexical state. */
  int GRAPH = 5;
  /** Lexical state. */
  int INAREA = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\":\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\":\"",
    "\"}\"",
    "\"]\"",
    "\"\\\"@graph\\\"\"",
    "\"\\\"@type\\\"\"",
    "\"\\\"title\\\"\"",
    "\"\\\"relation\\\"\"",
    "\"\\\"street-address\\\"\"",
    "\"\\\"area\\\"\"",
    "\"\\\"latitude\\\"\"",
    "\"\\\"longitude\\\"\"",
    "\"\\\"accesibility\\\"\"",
    "\"\\\"organization-name\\\"\"",
    "\"\\\"services\\\"\"",
    "\",\"",
    "<ORGANIZATION_STRING>",
    "\"\\\"@id\\\"\"",
    "\"[\"",
    "\"]\"",
    "<STRING>",
    "<INTEGER>",
    "<DOUBLE>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"\\\"@id\\\"\"",
    "<token of kind 37>",
  };

}
