/* Generated By:JavaCC: Do not edit this line. XMLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_CONCEPTS = 5;
  /** RegularExpression Id. */
  int OPEN_DATASETS = 6;
  /** RegularExpression Id. */
  int CATALOG = 7;
  /** RegularExpression Id. */
  int XMLNS = 8;
  /** RegularExpression Id. */
  int XMNLNS_XSI = 9;
  /** RegularExpression Id. */
  int XSI_SCHEMA_LOCATION = 10;
  /** RegularExpression Id. */
  int HEADER = 11;
  /** RegularExpression Id. */
  int OPEN_CONCEPT = 12;
  /** RegularExpression Id. */
  int OPEN_DATASET = 13;
  /** RegularExpression Id. */
  int CLOSE_CONCEPTS = 14;
  /** RegularExpression Id. */
  int CLOSE_DATASETS = 15;
  /** RegularExpression Id. */
  int CLOSE_CATALOG = 16;
  /** RegularExpression Id. */
  int CLOSE_CONCEPT = 17;
  /** RegularExpression Id. */
  int CLOSE_DATASET = 18;
  /** RegularExpression Id. */
  int OPEN_CODE = 19;
  /** RegularExpression Id. */
  int CLOSE_CODE = 20;
  /** RegularExpression Id. */
  int OPEN_LABEL = 21;
  /** RegularExpression Id. */
  int OPEN_TITLE = 22;
  /** RegularExpression Id. */
  int OPEN_DESCRIPTION = 23;
  /** RegularExpression Id. */
  int OPEN_KEYWORD = 24;
  /** RegularExpression Id. */
  int OPEN_THEME = 25;
  /** RegularExpression Id. */
  int OPEN_PUBLISHER = 26;
  /** RegularExpression Id. */
  int CLOSE_LABEL = 27;
  /** RegularExpression Id. */
  int CLOSE_TITLE = 28;
  /** RegularExpression Id. */
  int CLOSE_DESCRIPTION = 29;
  /** RegularExpression Id. */
  int CLOSE_KEYWORD = 30;
  /** RegularExpression Id. */
  int CLOSE_THEME = 31;
  /** RegularExpression Id. */
  int CLOSE_PUBLISHER = 32;
  /** RegularExpression Id. */
  int ID = 33;
  /** RegularExpression Id. */
  int VALUE_CODE = 34;
  /** RegularExpression Id. */
  int VALUE_LABEL = 35;
  /** RegularExpression Id. */
  int STRING = 36;
  /** RegularExpression Id. */
  int END_ELEMENT = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"<concepts>\"",
    "\"<datasets>\"",
    "\"<catalog\"",
    "\"xmlns=\"",
    "\"xmlns:xsi=\"",
    "\"xsi:schemaLocation=\"",
    "\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\"",
    "\"<concept\"",
    "\"<dataset\"",
    "\"</concepts>\"",
    "\"</datasets>\"",
    "\"</catalog>\"",
    "\"</concept>\"",
    "\"</dataset>\"",
    "\"<code\"",
    "\"/code>\"",
    "\"<label>\"",
    "\"<title>\"",
    "\"<description>\"",
    "\"<keyword>\"",
    "\"<theme>\"",
    "\"<publisher>\"",
    "\"</label>\"",
    "\"</title>\"",
    "\"</description>\"",
    "\"</keyword>\"",
    "\"</theme>\"",
    "\"</publisher>\"",
    "\"id=\"",
    "<VALUE_CODE>",
    "<VALUE_LABEL>",
    "<STRING>",
    "\">\"",
    "<token of kind 38>",
  };

}
