/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package piat.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FECHA = 5;
  /** RegularExpression Id. */
  int HORA = 6;
  /** RegularExpression Id. */
  int MSA = 7;
  /** RegularExpression Id. */
  int SMTP_IN = 8;
  /** RegularExpression Id. */
  int SMTP_OUT = 9;
  /** RegularExpression Id. */
  int SEC = 10;
  /** RegularExpression Id. */
  int TIPO = 11;
  /** RegularExpression Id. */
  int NUM = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int EOL = 14;
  /** RegularExpression Id. */
  int INFECTED = 15;
  /** RegularExpression Id. */
  int SPAM = 16;
  /** RegularExpression Id. */
  int OVERLOAD = 17;
  /** RegularExpression Id. */
  int BAD = 18;
  /** RegularExpression Id. */
  int REMIT = 19;
  /** RegularExpression Id. */
  int DOM = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int UNEXPECTED = 31;

  /** Lexical state. */
  int EN_TRAZA = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<FECHA>",
    "<HORA>",
    "\"msa\"",
    "\"smtp-in\"",
    "\"smtp-out\"",
    "<SEC>",
    "<TIPO>",
    "<NUM>",
    "<ID>",
    "<EOL>",
    "\"INFECTED\"",
    "\"SPAM\"",
    "\"overload\"",
    "\"bad\"",
    "<REMIT>",
    "<DOM>",
    "\":\"",
    "\"message-from: <\"",
    "\">\"",
    "\"to: <\"",
    "\"message-id:\"",
    "\"size:\"",
    "\"relay to:\"",
    "\"security-antivirus:\"",
    "\"SEC-PASSED: security-antispam:\"",
    "\"destination mailbox address\"",
    "<UNEXPECTED>",
  };

}
