/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package piat.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int LETRA = 6;
  /** RegularExpression Id. */
  int IDENTIFICADOR_TRAZA = 7;
  /** RegularExpression Id. */
  int PUNTO = 8;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 9;
  /** RegularExpression Id. */
  int GUION = 10;
  /** RegularExpression Id. */
  int GUION_BAJO = 11;
  /** RegularExpression Id. */
  int ARROBA = 12;
  /** RegularExpression Id. */
  int IGUAL = 13;
  /** RegularExpression Id. */
  int ABRE_PARENTESIS = 14;
  /** RegularExpression Id. */
  int CIERRA_PARENTESIS = 15;
  /** RegularExpression Id. */
  int COMA = 16;
  /** RegularExpression Id. */
  int MENOR_QUE = 17;
  /** RegularExpression Id. */
  int MAYOR_QUE = 18;
  /** RegularExpression Id. */
  int OVERLOAD = 19;
  /** RegularExpression Id. */
  int BAD = 20;
  /** RegularExpression Id. */
  int EOL = 21;
  /** RegularExpression Id. */
  int FECHA = 22;
  /** RegularExpression Id. */
  int HORA = 23;
  /** RegularExpression Id. */
  int MSA = 24;
  /** RegularExpression Id. */
  int SMTP_IN = 25;
  /** RegularExpression Id. */
  int SMTP_OUT = 26;
  /** RegularExpression Id. */
  int SEC = 27;
  /** RegularExpression Id. */
  int USER_MAILBOX = 28;
  /** RegularExpression Id. */
  int INFECTED = 29;
  /** RegularExpression Id. */
  int SEC_PASSED = 30;
  /** RegularExpression Id. */
  int REMIT = 31;
  /** RegularExpression Id. */
  int DOM = 32;
  /** RegularExpression Id. */
  int FROM = 33;
  /** RegularExpression Id. */
  int RELAY_TO = 34;
  /** RegularExpression Id. */
  int SPAM = 35;
  /** RegularExpression Id. */
  int UNEXPECTED = 36;

  /** Lexical state. */
  int PASS = 0;
  /** Lexical state. */
  int OUT = 1;
  /** Lexical state. */
  int GEN = 2;
  /** Lexical state. */
  int SECURITY = 3;
  /** Lexical state. */
  int SERVER = 4;
  /** Lexical state. */
  int DEFAULT = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"bounced from:\"",
    "<NUMERO>",
    "<LETRA>",
    "<IDENTIFICADOR_TRAZA>",
    "\".\"",
    "\":\"",
    "\"-\"",
    "\"_\"",
    "\"@\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"overload)\"",
    "\"(bad destination mailbox address)\"",
    "\"\\n\"",
    "<FECHA>",
    "<HORA>",
    "\"msa\"",
    "\"smtp-in\"",
    "\"smtp-out\"",
    "<SEC>",
    "\"user-mailbox\"",
    "\"security-antivirus: INFECTED\"",
    "\"SEC-PASSED:\"",
    "<REMIT>",
    "<DOM>",
    "\"message from:\"",
    "\"relay to:\"",
    "\"security-antispam: SPAM\"",
    "<UNEXPECTED>",
  };

}
