/* Generated By:JavaCC: Do not edit this line. XMLParserTreeConstants.java Version 7.0.12 */
public interface XMLParserTreeConstants
{
  public int JJTDOCUMENT = 0;
  public int JJTCONCEPTS = 1;
  public int JJTCONCEPT = 2;
  public int JJTELEMENT = 3;


  public String[] jjtNodeName = {
    "document",
    "concepts",
    "concept",
    "element",
  };
}
/* JavaCC - OriginalChecksum=7ca884af42dfff8211ebdaf76678a0ea (do not edit this line) */
