/* Generated By:JJTree&JavaCC: Do not edit this line. XMLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOSE_CONCEPTS = 5;
  /** RegularExpression Id. */
  int OPEN_CONCEPT = 6;
  /** RegularExpression Id. */
  int OPEN_CODE = 7;
  /** RegularExpression Id. */
  int CLOSE_CODE = 8;
  /** RegularExpression Id. */
  int OPEN_LABEL = 9;
  /** RegularExpression Id. */
  int CLOSE_LABEL = 10;
  /** RegularExpression Id. */
  int TAG_CONTENT = 11;
  /** RegularExpression Id. */
  int OPEN_CONCEPTS = 12;
  /** RegularExpression Id. */
  int CLOSE_CONCEPT = 13;

  /** Lexical state. */
  int CONCEPT = 0;
  /** Lexical state. */
  int CONCEPTS = 1;
  /** Lexical state. */
  int DEFAULT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"</concepts>\"",
    "\"<concept>\"",
    "\"<code>\"",
    "\"</code>\"",
    "\"<label>\"",
    "\"</label>\"",
    "<TAG_CONTENT>",
    "\"<concepts>\"",
    "\"</concept>\"",
  };

}
